### ISSUE TITLE
add shiny server as a deployment option for ambiorix apps

### ISSUE THREAD

**Issue by kennedymwavu** [devOpifex/ambiorix-site#8]
ambiorix apps can be deployed using [shiny server](https://docs.posit.co/shiny-server/#getting-started), which is already familiar to many R users. this offers a lower learning curve compared to docker-based deployments and could serve as a great entry point for users who are less experienced with docker.

let's include it as one of the deployment options in the docs. however, we should make it clear that while the open-source version of shiny server works well for most users, some advanced functionality (such as managing the number of R processes, load balancing, etc.) will require shiny server professional. in the long run, users would benefit from learning how to implement these features independently, especially for more control & flexibility.

**Comment by JohnCoene** [comment]
Wait, it can? I was sure I tried and it did not work. Perhaps I have to try Posit Connect again then!

**Comment by JohnCoene** [comment]
Wait, it can?! I was sure I tried and it did not work. Perhaps I have to try Posit Connect again then!

**Comment by kennedymwavu** [comment]
yes, it does! before shiny server starts an R process, it sets the `SHINY_PORT` & `SHINY_HOST` env vars.
that means we can check for the `SHINY_PORT` env var before starting an ambiorix app.
`SHINY_HOST` defaults to `0.0.0.0`, same as ambiorix so no need to worry about it.

a short reprex...

i have this at `/home/mwavu/projects/random`:

```r
library(ambiorix)
library(htmltools)

home_get <- \(req, res) {
  html <- tags$h3("Yes, Ambiorix IN Shiny Server!")
  res$set_status(200L)$send(html)
}

home_post <- \(req, res) {
  response <- list(
    code = 200L,
    msg = "An API too!"
  )
  res$set_status(200L)$json(response)
}

contact_get <- \(req, res) {
  html <- tags$h3("Our contact page")
  res$set_status(200L)$send(html)
}

contact_post <- \(req, res) {
  response <- list(
    code = 200L,
    msg = "Running in Shiny Server"
  )
  res$set_status(200L)$json(response)
}

port <- Sys.getenv("SHINY_PORT")

Ambiorix$
  new(port = port)$
  get("/", home_get)$
  post("/", home_post)$
  get("/contact", contact_get)$
  post("/contact", contact_post)$
  start()
```

here is my `/etc/shiny-server/shiny-server.conf`:

```nginx
run_as mwavu;

server {
  listen 3838;

  # define a location at the base URL
  location / {

    # host the directory of shiny apps stored in this dir:
    site_dir /home/mwavu/projects;

    # log dir:
    log_dir /var/log/shiny-server;

    # ...my other configs...
  }
}
```

restart shiny server and now visit `http://localhost:3838/random`. you should see "Yes, Ambiorix IN Shiny Server".

works with curl too:
![image](https://github.com/user-attachments/assets/aca6fa52-ffda-48cd-b4df-a1c2671cf052)

**Comment by JohnCoene** [comment]
Oh man, super neat, thanks for checking this!!! Definitely worth documenting

**Comment by kennedymwavu** [comment]
one small challenge when hosting a frontend built using ambiorix on shiny server is handling internal links and requests. normally, you'd set the `href` attributes of anchor tags to something like `/about` or `/contact` to link to the different endpoints within the same app.

however, when the app is hosted on shiny server at url like `http://localhost:3838/app-name`, using `/about` as the link will direct the browser to `http://localhost:3838/about` (outside your app), which isn't what you intend.

to fix this, you need to prepend the app name to the `href` values, like `href = "/app-name/about"`. this ensures the links point the browser to the correct routes within your app.

this same solution should also be used if you're working with [htmx](https://htmx.org/), [datatables](https://datatables.net/), etc. 

i will leave these helper functions here for posterity:

```r
#' Get port which shiny server has passed to app
#'
#' @return String.
#' @export
get_shiny_server_port <- \() {
  Sys.getenv("SHINY_PORT")
}

#' Is app running in shiny server?
#'
#' @details Checks for the env var `SHINY_PORT`.
#' @return Logical.
#' @export
running_in_shiny_server <- \() {
  !identical(get_shiny_server_port(), "")
}

#' Get port to run app on
#'
#' @details If app is not running in shiny server,
#' the port defaults to `default`.
#' @param default Integer. Default port to run app on.
#' @return Integer.
#' @export
get_port <- \(default = 5000L) {
  if (running_in_shiny_server()) {
    return(as.integer(get_shiny_server_port()))
  }
  default
}

#' Get name used by shiny server to serve this app
#'
#' @details Checks for the env var `APP_NAME`. It should
#' be something along the lines of "/app-name" meaning
#' you can access the app if you navigate to "http://localhost:3838/app-name".
#' @return String
#' @export
get_app_name <- \() {
  if (!running_in_shiny_server()) {
    return("")
  }

  name <- Sys.getenv("APP_NAME")
  if (identical(name, "")) {
    msg <- paste(
      "App is running in shiny server but env var 'APP_NAME' not found.",
      "Please set it in your `.Renviron`."
    )
    stop(msg, call. = FALSE)
  }
  name
}

#' Create an anchor tag's href
#'
#' @details If the application is running in shiny server, then the `APP_NAME` env var is
#' prefixed to the `href`.
#' @param x String. 'href' attribute of an anchor tag.
#' @export
create_href <- \(href) {
  if (running_in_shiny_server()) {
    href <- paste0(get_app_name(), href)
  }
  href
}
```

**Comment by kennedymwavu** [comment]
it turns out with that same solution, we can deploy ambiorix apps & APIs to [shinyapps.io](https://shinyapps.io/).
check out this example app: [hello](https://mwavu.shinyapps.io/hello/)
